name: "Feature request"
description: Suggest an idea for this project
title: "[feat] <short description>"
labels: ["enhancement"]
assignees: []
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-check
      options:
        - label: I have searched existing issues and discussions to avoid duplicates
          required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What problem or use case does this feature address?
      placeholder: Describe the underlying need rather than the solution.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your idea. Include API shape, UX, or examples if relevant.
      placeholder: Outline the approach, alternatives considered, and trade-offs.
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: Impact and risks
      description: Performance, security, or compatibility considerations.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, prototypes, or screenshots.